---
- name: Install Tomcat
  hosts: localhost
  become: yes
  tasks:
    - name: Install Java
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Create a group for Tomcat
      group:
        name: tomcat
        state: present

    - name: Create a user for Tomcat
      user:
        name: tomcat
        group: tomcat
        shell: /bin/false

    - name: Download Tomcat
      get_url:
        url: https://downloads.apache.org/tomcat/tomcat-10/v10.1.25/bin/apache-tomcat-10.1.25.tar.gz
        dest: /tmp/apache-tomcat-10.1.25.tar.gz

    - name: Extract Tomcat
      unarchive:
        src: /tmp/apache-tomcat-10.1.25.tar.gz
        dest: /opt/tomcat2
        remote_src: yes

    - name: Change ownership of Tomcat directory
      file:
        path: /opt/tomcat2/apache-tomcat-10.1.25
        owner: tomcat
        group: tomcat
        recurse: yes

    - name: Create a symbolic link to Tomcat
      file:
        src: /opt/tomcat2/apache-tomcat-10.1.25
        dest: /opt/tomcat2/
        state: link

    - name: Create a systemd service file for Tomcat
      copy: 
        dest: /etc/systemd/system/tomcat.service
        content: |
          [Unit]
          Description=Apache Tomcat Web Application Container
          After=network.target

          [Service]
          Type=forking

          Environment=JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
          Environment=CATALINA_PID=/opt/tomcat2/temp/tomcat.pid
          Environment=CATALINA_HOME=/opt/tomcat2
          Environment=CATALINA_BASE=/opt/tomcat2
          Environment='CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC'
          Environment='JAVA_OPTS=-Djava.awt.headless=true -Djava.security.egd=file:/dev/./urandom'

          ExecStart=/opt/tomcat2/bin/startup.sh
          ExecStop=/opt/tomcat2/bin/shutdown.sh

          User=tomcat
          Group=tomcat
          UMask=0007
          RestartSec=10
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd to apply changes
      systemd:
        daemon_reload: yes

    - name: Start Tomcat service
      systemd:
        name: tomcat
        state: started
        enabled: yes

