name: maven job

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  Build:
    name: Build
    runs-on: [ self-hosted, surya ]
    steps:
      - uses: actions/checkout@v2
      - name: Docker run
        run: |
          docker build -t tomcat-apache .
          docker run -d --name my-tomcat-container -p 9091:8080 tomcat-apache
