name: maven job

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  Build:
    name: Build
    runs-on: [ self-hosted, surya, siddhu ]
    steps:
      - uses: actions/checkout@v2
      - name: Build with Maven
        run: cd /home/adduser/siddhu/jenkins/java-app/my-web-app;
             mvn clean package